website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

app_name = 'website'  # URL namespace

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(redirect_authenticated_user=True),
         name='login'),
    path('signup/', views.SignUpPage.as_view(), name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.Index.as_view(), name='index'),
    path('events/', views.EventIndex.as_view(), name='event_index'),
    path('events/<slug:slug>-<int:event_id>/',
         views.EventPage.as_view(),
         name='event_page'),
    path('events/create',
         staff_member_required(views.EventCreate.as_view()),
         name='event_create'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('events/<slug:slug>-<int:event_id>/status-email-preview',
         staff_member_required(views.VolunteerStatusEmailPreview.as_view()),
         name='volunteer_email_preview'),
    path('events/<slug:slug>-<int:event_id>/registration',
         views.RegistrationPage.as_view(),
         name='registration'),
    path('events/<slug:slug>-<int:event_id>/assign-volunteers',
         staff_member_required(views.EventAssignVolunteers.as_view()),
         name='assign_volunteers'),
    path('events/<slug:slug>-<int:event_id>/workshop_create',
         staff_member_required(views.WorkshopCreate.as_view()),
         name="workshop_create"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('profile/',
    #     views.user_profile,
    #     name='profile'), # profile page view (currently not used)
]

# Nginx will serve the media root in production
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/views.py
"""
Compclub website Views.

Contains functions to render views (i.e. pages) to the user as HTTP responses.
For more information, see
https://docs.djangoproject.com/en/2.1/topics/http/views/
"""
import logging
from collections import namedtuple
from datetime import datetime, date
from smtplib import SMTPSenderRefused

from content_editor.contents import contents_for_item
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.core.mail import BadHeaderError, send_mass_mail
from django.db import transaction
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.html import mark_safe
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import Http404
from django.contrib.humanize.templatetags.humanize import ordinal
import calendar

from website.forms import (CreateStudentForm, CreateUserForm, EventForm,
                           RegistrationForm, VolunteerAssignForm, WorkshopForm)
from website.models import (Download, Event, LightBox, NoEmbed, Registration,
                            RichText, Workshop)
from website.plugins import cms
from website.utils import generate_status_email

logger = logging.getLogger(__name__)
DISPLAY_ERROR = "$DISPLAY_ERROR$"


class Index(ListView):
    """
    Renders the home page to the user.

    Home page shows all the basic information of the website

    Args:
        request: HTTP request header contents

    Returns:
        HTTP response containing home page

    """

    model = Event
    template_name = 'website/index.html'

    def get_context_data(self, **kwargs):
        """Return current/future events sorted by start date."""
        context = super().get_context_data(**kwargs)

        context['events_list'] = Event.objects.filter(
            highlighted_event=True,
            finish_date__gte=datetime.now()
        ) .order_by('start_date')

        return context


class EventIndex(ListView):
    """
    Render and show events page to the user.

    Events page shows list of current and future events, and how many workshops
    they consist of.

    Args:
        request: HTTP request header contents

    Returns:
        HTTP response containing events page

    """

    model = Event
    template_name = 'website/event_index.html'

    def get_context_data(self, **kwargs):
        """Return future events sorted by start date."""
        context = super().get_context_data(**kwargs)

        context['events_list'] = Event.objects \
            .filter(finish_date__gte=datetime.now()) \
            .annotate(n_workshops=Count('workshop')) \
            .order_by('start_date')

        return context


class EventPage(PermissionRequiredMixin, DetailView):
    """
    Render and show event detail page to the user.

    Event page shows specific and detailed information about a particular
    event.

    Args:
        request: HTTP request header contents
        event_id: the unique ID of the event
        slug: the human-readable event name in the URL

    Returns:
        HTTP response containing the event detail page

    """

    model = Event
    context_object_name = 'event'
    template_name = 'website/event.html'
    permission_required = ("website.view_event")
    permission_denied_message = "Event does not exist or you don't have permissions to view the event."   # noqa: E501
    unreleased_message = "Event hasn't started yet! It will be available {}{} 😄"   # noqa: E501

    def get_context_data(self, **kwargs):  # noqa: D102
        context = super().get_context_data(**kwargs)
        return context

    def get(self, request, event_id, slug):  # noqa: D102
        # check if url is valid
        event = get_object_or_404(Event, pk=event_id)

        if (event.hidden_event and not self.request.user.has_perms(
                "website.view_hidden_event")):
            self.handle_no_permission()

        if event.slug != slug:
            return redirect('website:event_page',
                            event_id=event.pk,
                            slug=event.slug)

        # Not start date yet
        if (date.today() < event.start_date and not self.request.user.has_perm(
                "website.view_unreleased_event")):
            raise Http404(
                self.get_unreleased_message().format(
                    f"from {ordinal(event.start_date.day)} ",
                    calendar.month_name[event.start_date.month]))

        # Unreleased
        if (not event.released and not self.request.user.has_perm(
                "website.view_unreleased_event")):
            raise Http404(self.get_unreleased_message().format("", "soon"))

        contents = contents_for_item(
            event, [RichText, Download, NoEmbed, LightBox])
        return render(request, self.template_name, {
            "event": event,
            "content": {
                region.key: mark_safe(
                    "".join(self._render_elements(contents[region.key])))
                for region in event.regions
            },
        })

    def _render_elements(self, elements):
        """Render django-content-editor elements."""
        for element in elements:
            if isinstance(element, RichText):
                yield cms.render_rich_text(element)
            elif isinstance(element, Download):
                yield cms.render_download(element)
            elif isinstance(element, NoEmbed):
                yield cms.render_noembed(element)
            elif isinstance(element, LightBox):
                yield cms.render_lightbox(element)

    def get_unreleased_message(self):
        """Get the unreleased event message."""
        return DISPLAY_ERROR + self.unreleased_message

    def get_permission_denied_message(self):
        """Get the permission denied message.

        This error message is only for debugging and shouldn't display since
        it provides information to unauthorized users.
        """
        return self.permission_denied_message

    def handle_no_permission(self):
        """Redirect if no permissions to view page."""
        raise Http404(self.get_permission_denied_message())


class SignUpPage(CreateView):
    """
    Render and show student sign up form to the user.

    The sign up form allows students to sign up to CompClub generally.

    Args:
        request: HTTP request header contents

    Returns:
        HTTP response containing the Sign Up form for the given event

    """

    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        """Add both forms to context."""
        if "user_form" not in kwargs:
            kwargs["user_form"] = CreateUserForm()
        if "student_form" not in kwargs:
            kwargs["student_form"] = CreateStudentForm()
        if "student_form" not in kwargs:
            kwargs["student_form"] = CreateStudentForm()

        return kwargs

    def get(self, request, *args, **kwargs):
        """Render form."""
        return render(request, self.template_name, self.get_context_data())

    def post(self, request, *args, **kwargs):
        """Handle both form requests."""
        ctx = {}
        user_form = CreateUserForm(data=request.POST)
        student_form = CreateStudentForm(data=request.POST)

        with transaction.atomic():
            if user_form.is_valid() and student_form.is_valid():
                # Create user
                user = user_form.save()

                student_group, _existed = Group.objects.get_or_create(
                    name="default_student")
                user.groups.add(student_group)

                # Create student
                student = student_form.save(commit=False)
                student.user = user
                student.save()

                # Sign in and redirect
                login(request, user)
                return redirect('website:event_index')

        ctx["user_form"] = CreateUserForm(request.POST)
        ctx["student_form"] = CreateStudentForm(request.POST)

        return render(
            request,
            self.template_name,
            self.get_context_data(
                **ctx))


class RegistrationPage(CreateView):
    """
    Render and show event registration form to the user.

    The registration form allows students to register interest for a particular
    event.

    Args:
        request: HTTP request header contents
        event_id: the unique ID of the event
        slug: the human-readable event name in the URL

    Returns:
        HTTP response containing the registration form for the given event

    """

    form_class = RegistrationForm
    template_name = 'website/registration_form.html'
    model = Registration

    def get_context_data(self, **kwargs):  # noqa: D102
        context = super().get_context_data(**kwargs)

        event = Event.objects.get(id=self.kwargs['event_id'])
        registration_form = self.get_form()
        registration_form.fields['event'].initial = event

        context['registration_form'] = registration_form
        context['event'] = event

        return context

    def get(self, request, event_id, slug):  # noqa: D102
        # check if url is valid
        event = get_object_or_404(Event, pk=event_id)
        if event.slug != slug:
            return redirect('website:registration',
                            event_id=event.pk,
                            slug=event.slug)

        return super().get(request, event_id, slug)

    def get_success_url(self):  # noqa: D102
        return reverse('website:event_page', kwargs=self.kwargs)


class EventCreate(CreateView):
    """
    Render and show an event creation form.

website/templates/website/Registration_form.html
{% extends "website/default.html" %}

{% block title %} {{ block.super }} -- Volunteer Registration {% endblock %}


{% block content %}
  {{ block.super }}
  <div class="container">
        <div class="event-list-header">
          <h1 class="event-list-title">Registration</h1>
        </div>
        <div class="event-card">
            <div class="event-card-container">
                    <table class="table">
                            <thead class="thead-dark">
                              <tr>
                                <th scope="col">Event Name</th>
                                <th scope="col">Date</th>
                              </tr>
                            </thead>
                        {% if event %}
                              <tbody>
                                <tr class="table-active">
                                  <td>{{event.name }}</td>
                                  <td>{{event.start_date }} to {{event.finish_date }}</td>
                                </tr>
                              </tbody>
                        {% else %}
                          <p>To be confirmed</p>
                        {% endif %}
                      </table>
                <form method='post' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
                    {{ registration_form }}
                    <button type="submit" class="btn btn-outline-warning">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/website/about.html
{% extends "website/default.html" %}
{% load static %}

{% block title %} {{ block.super }} - About Us {% endblock %}

{% block content %}
    {{block.super}}
  <!-- block.super calls everything in the inherited file, then adds on after -->
  <!-- About Section -->
  <div class="container">
    <div class="ml-0 pt-2 pt-lg-3 pl-lg-3">
      <h1 class="font-weight-lighter display-4 underline">One Skill. Infinite Opportunities.</h1>
    </div>
    <div class="about-container">
      <div class="about-banner">
        <img src="{% static 'website/winterworkshop.jpg' %}" alt="CSESoc Winter Workshop, July 2018" class="about-banner-img">
      </div>
      <div class="about-body">
        <div class="about-mission">
          <h2>Our mission is to inspire and engage high school students to explore the broad field of Computer Science.</h2>
        </div>
        <div class="about-description">
          <h3>About us</h3>
          <p>
            CompClub is a high school outreach program of the Computer Science and Engineering Student Society (CSESoc) at UNSW Sydney.
          </p><p>
            From robotics to computer games workshops, we hope to spark the interests of those who are just starting their journey into Computer Science whilst also providing depth for those who have excelled beyond the classroom.
          </p><p>
            CompClub organises biannual Summer and Winter workshops, taught at UNSW, covering a wide variety of topics in the computing world. We also run standalone and weekly workshops throughout the year at UNSW and participating high schools. 
          </p><p>
            We believe that anyone can code, and everyone should have the opportunity to try. Our workshops are mentored by current computing students at the University of New South Wales. 
          </p><p>
            Computer Science is a broad topic with fields in Robotics, Security, Computer Graphics, Game design and many more. We hope to show students from all disciplines how a knowledge of computing can help them in the future. <i class="fas fa-square"></i>
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/website/base.html
{% load static %}
{% load compress %}
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>
    {% block title %}CSESoc CompClub{% endblock %}
  </title>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="description" content="CSESoc CompClub provides opportunities for students to learn new practical coding skills.">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Favicons -->
  <link rel="icon" type="image/png" href="{% static 'favicon-32x32.png' %}" sizes="32x32" />
  <link rel="icon" type="image/png" href="{% static 'favicon-16x16.png' %}" sizes="16x16" />
  <link rel="shortcut icon" type="image/png"  href="{% static 'favicon.ico' %}" />

  <!-- Fontawesome CSS -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/solid.css"
    integrity="sha384-wnAC7ln+XN0UKdcPvJvtqIH3jOjs9pnKnq9qX68ImXvOGz2JuFoEiCjT8jyZQX2z" crossorigin="anonymous"
    media="print" onload="this.media='all'">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/fontawesome.css"
    integrity="sha384-HbmWTHay9psM8qyzEKPc8odH4DsOuzdejtnr+OFtDmOcIVnhgReQ4GZBH7uwcjf6" crossorigin="anonymous"
    media="print" onload="this.media='all'">
  <!-- jquery confirm CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.css"
    media="print" onload="this.media='all'">
  {% compress css %}
  <link type="text/x-scss" rel="stylesheet" href="{% static 'website/style.scss' %}">
  {% endcompress %}
</head>

<body>
  {% block content %}{% endblock %}
  <!-- Optional JavaScript -->

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <!-- jquery-confirm JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>
  <!-- lightbox javascript -->
  <script src="{% static 'website/js/fslightbox.js' %}" async></script>

  {% block scripts %}
  {% endblock %}
</body>

</html>

website/templates/website/default.html
{% extends "website/base.html" %}
{% load static %}

{% block content %}
<!-- navbar -->
{% include "website/navbar.html" %}

{% block body %}
{% endblock %}

{% endblock %}

website/templates/website/event.html
{% extends "website/default.html" %}
{% load static %}

{% block title %} {{ block.super }} - Workshop {% endblock %}

{% block content %}
{{ block.super }}
<div class="container">
  <div class="header">
    <h1 class="title">{{ event.name }}</h1>
  </div>
  <p>{{ content.main }}</p>

  <!-- comment section -->
  <div id="wpac-comment"></div>
  <script type="text/javascript">
  wpac_init = window.wpac_init || [];
  wpac_init.push({widget: 'Comment', id: 25587});
  (function() {
      if ('WIDGETPACK_LOADED' in window) return;
      WIDGETPACK_LOADED = true;
      var mc = document.createElement('script');
      mc.type = 'text/javascript';
      mc.async = true;
      mc.src = 'https://embed.widgetpack.com/widget.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(mc, s.nextSibling);
  })();
  </script>
  <br>
  <br>
</div>

{% endblock %}

{% block scripts %}
<!-- lightbox javascript -->
<script src="{% static 'website/js/fslightbox.js' %}" async></script>
{% endblock %}

website/templates/website/event_card.html
{% comment %}
Requires an event to be passed in.
{% endcomment%}
<div class="event-holder">
    <div class="calendar">
    {% if event.n_workshops > 1 %}
    <div class="calendar-container calendar-from">
        <h3 class="calendar-month">{{ event.start_date|date:"M" }}</h3>
        <p class="calendar-day">{{ event.start_date|date:"d" }} </p>
    </div>
    <p class="calendar-divider">&#8212;</p>
    <div class="calendar-container calendar-to">
        <h3 class="calendar-month">{{ event.finish_date|date:"M" }}</h3>
        <p class="calendar-day">{{ event.finish_date|date:"d" }} </p>
    </div>
    <h5 class="calendar-nworkshops">{{ event.n_workshops }} Workshops</h5>
    {% else %}
    <div class="calendar-container calendar-to">
        <h3 class="calendar-month">{{ event.start_date|date:"M" }}</h3>
        <p class="calendar-day">{{ event.start_date|date:"d" }} </p>
    </div>
    {% endif %}
    </div>
    <div class="event-list-card">
    <div class="event-card-container">
        <a href="{% url 'website:event_page' slug=event.slug event_id=event.pk %}">
        <h2 class="event-card-title">{{ event.name }}</h2>
        </a>
        <div class="event-card-footer">
        <a class="event-button right" href="{% url 'website:event_page' slug=event.slug event_id=event.pk %}">
            <i class="fas fa-link"></i> Learn more
        </a>
        </div>
    </div>
    </div>
</div>

website/templates/website/event_create.html
{% extends "website/default.html" %}
{% load widget_mods %}

{% block title %} {{ block.super }} - Create Event {% endblock %}

{% block content %}
{{ block.super }}
<div class="container">
  <h3 class="display-3 mb-3 mt-3">Create event</h3>

  <form class="event-form" method="post" novalidate>
    {% csrf_token %}

    {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endfor %}

    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    <div class="form-group">
      {{ form.name.label_tag }}
      {% if form.name.errors %}
      {% comment %}With the custom filter "add_attr" we can put extra css
      classes to this form field{% endcomment %}
      {{ form.name|add_attrs:"placeholder:Event title, is-invalid" }}
      {% for error in form.name.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
      {% endfor %}
      {% else %}
      {{ form.name|add_attrs:"placeholder:Event title" }}
      {% endif %}
    </div>

    <div class="form-row">

      <div class="form-group col-md-4">
        {{ form.start_date.label_tag }}
        {% if form.start_date.errors %}
        {{ form.start_date|add_attrs:"is-invalid" }}
        {% for error in form.start_date.errors %}
        <div class="invalid-feedback">
          {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {{ form.start_date }}
        {% endif %}
        <small class="form-text text-muted">
          {{ form.start_date.help_text }}
        </small>
      </div>

      <div class="form-group col-md-4">
        {{ form.finish_date.label_tag }}
        {% if form.finish_date.errors %}
        {{ form.finish_date|add_attrs:"is-invalid" }}
        {% for error in form.finish_date.errors %}
        <div class="invalid-feedback">
          {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {{ form.finish_date }}
        {% endif %}
        <small class="form-text text-muted">
          {{ form.finish_date.help_text }}
        </small>
      </div>

      <div class="form-group col-md-4">
        <label for="{{ form.owner.id_for_label }}">{{ form.owner.label }}:</label>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroupPrepend">@</span>
          </div>
          {% if form.owner.errors %}
          {{ form.owner|add_attrs:"is-invalid" }}
          {% for error in form.owner.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
          {% endfor %}
          {% else %}
          {{ form.owner }}
          {% endif %}
        </div>
        <small class="form-text text-muted">
          {{ form.owner.help_text }}
        </small>
      </div>

    </div>

    <div class="form-group">
      {{ form.description.label_tag }}
      {% if form.description.errors %}
      {{ form.description|add_attrs:"rows:3, cols:10, is-invalid" }}
      {% for error in form.description.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
      {% endfor %}
      {% else %}
      {{ form.description }}
      {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
</div>
{% endblock %}

website/templates/website/navbar.html
{% load static %}
<nav class="navbar navbar-light navbar-expand-lg">
  <div class="navbar-header">
    <a href="{% url 'website:index' %}" class="navbar-brand" href="#home">
      <img src="{% static 'website/index/compclub-logo.png' %}" alt="CSESoc CompClub" class="img-responsive"
        style="margin:5%">
    </a>
  </div>
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-items collapse navbar-collapse page-scroll col-12" id="navbarNavDropdown">
    <ul class="navbar-nav mt-2 mt-lg-0 ">
      {% if request.resolver_match.url_name == 'index'%}
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a class="page-scroll" href="#about">About</a>
          </li>
          <li>
            <a class="page-scroll" href="#workshops">Workshops</a>
          </li>
          <li>
            <a class="page-scroll" href="#initiatives">Initiatives</a>
          </li>
          <li>
            <a class="page-scroll" href="#contact">Contact</a>
          </li>
        </ul>
      </div>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:index' %}">Home</a>
      </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav mt-2 mt-lg-0 ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:event_index' %}">Events</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" id="accountDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle"></i>
          {% if request.user.first_name %}
          {{ request.user.first_name }}
          {% else %}
          {{ request.user.username }}
          {% endif %}
        </a>
        <div class="dropdown-menu" aria-labelledby="accountDropdown">
          <a href="{% url 'website:logout' %}" class="dropdown-item">Logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link cta-link" href="{% url 'website:signup' %}">Sign Up</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

website/templates/website/profile.html
<html>
<a href="{% url 'website:logout' %}">Logout</a>
<h3>{{ request.user.username }}</h3>

</html>

website/templates/website/registration_form.html
{% extends "website/default.html" %}

{% block title %} {{ block.super }} -- Volunteer Registration {% endblock %}


{% block content %}
{{ block.super }}
<div class="container">
  <div class="event-list-header">
    <h1 class="event-list-title">Registration</h1>
  </div>
  <div class="event-detail-card">
    <div class="event-card-container">
      {% include 'website/components/event_table.html' %}
      <form method='post' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
        {{ registration_form }}
        <button type="submit" class="btn btn-outline-warning">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/signups.html
{% extends "website/default.html" %}

{% block title %} {{ block.super }} - Signups {% endblock %}

{% block body %}
<div class="container">
  <div class="header">
    <h1 class="title">Sign-ups</h1>
  </div>

  {% for event in events %}
    <div class="signup-event-container">
      <div class="signup-event-content">
	<div class="signup-event-header">
	  <a href="{% url 'website:event_page' slug=event.slug event_id=event.pk %}">{{ event.name }}</a>
	</div>
	<div class="row table-container">
	  <div class="col">
	    <div class="signup-event-subheader">Volunteers</div>
	    <table class="prettify-table">
	      <thead>
		<tr>
		  <th scope="col">#</th>
		  <th scope="col">First Name</th>
		  <th scope="col">Last Name</th>
		  <th scope="col">E-mail</th>
		</tr>
	      </thead>

	      <tbody>
	      {% for volunteer in event.assigned.all %}
		<tr>
		  <th scope="row">{{ forloop.counter }} </th>
		  <td>{{ volunteer.user.first_name }} </td>
		  <td>{{ volunteer.user.last_name }}</td>
		  <td>
		    <a href="mailto:{{ volunteer.user.email }}">
		      {{ volunteer.user.email }}
		    </a>
		  </td>
		</tr>
	      {% endfor %}
	      </tbody>
	    </table>
	  </div>
	</div>

	<div class="row table-container">
	  <div class="col">
	    <div class="signup-event-subheader">Students</div>
	    <table class="table table-borderless prettify-table">
	      <thead>
		<tr>
		  <th scope="col">#</th>
		  <th scope="col">Name</th>
		  <th scope="col">E-mail</th>
		  <th scope="col">Phone Number</th>
		  <th scope="col">Parent E-mail</th>
		  <th scope="col">Parent Number</th>
		</tr>
	      </thead>
	      <tbody>
		{% for registered_user in event.registration_set.all %}
		  <tr>
		    <th scope="row">{{ forloop.counter }}</th>
		    <td>{{ registered_user.name }}</td>
		    <td>
		      <a href="mailto:{{ registered_user.email }}">
			{{ registered_user.email }}
		      </a>
		    </td>
		    <td>{{ registered_user.number }}</td>
		    <td>
		      <a href="mailto:{{ registered_user.parent_email }}">
			{{ registered_user.parent_email }}
		      </a>
		    </td>
		    <td>{{ registered_user.parent_number }}</td>
		  </tr>
		{% endfor %}
	      </tbody>
	    </table>
	  </div>
	</div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

website/templates/website/volunteer_status_email_preview.html
{% extends "website/default.html" %}

{% block title %} {{ block.super }} - Email preview {% endblock %}

{% block content %}
{{ block.super }}
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody>
      {% for email in emails %}
      <tr>
        <th scope="row">{{ email.3.0 }}</th>
        <td>{{ email.1|safe }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <form method="POST">
    {% csrf_token %}
    <button class="btn" type="submit">Send</button>
  </form>
</div>
{% endblock %}

website/templates/website/workshop_create.html
{% extends "website/default.html" %}
{% load widget_mods %}

{% block title %} {{ block.super }} - Create Workshop {% endblock %}

{% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h3 class="display-3 mb-3 mt-3">Create workshop</h3>
      {% include 'website/components/event_table.html' %}
      <form method="post" class="workshop-form">
        {% csrf_token %}
        {{ workshop_form }}
        <br>
        <button type="submit" class="btn btn-primary">Create</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}